version: '3.8'

services:
  nodeapp:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      mongodb:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/countries
      - ELASTICSEARCH_URI=http://elasticsearch:9200
    networks:
      - app-network

  mongodb:
    image: "mongodb/mongodb-community-server:latest"
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - app-network
    volumes:
      - mongodb-data:/data/db

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.13.2"
    environment:
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - app-network
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
  elasticsearch-data:
